language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
services:
  - redis-server
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
