language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
services:
  - redis-server
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check -D travis=true
after_success:
  - bash <(curl -s https://codecov.io/bash)
