package io.github.kigsmtua.milau.task;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.github.kigsmtua.milau.task.Task;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Task classUnderTest = new Task();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
