package io.github.kigsmtua.milau.task;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Job {
    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {
        System.out.println(new Job().getGreeting());
        System.out.println("Welcome to milau...");
    }
}

