package com.milau.task;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import io.github.kigsmtua.milau.task.Job;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Job classUnderTest = new Job();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
